# Generated by Django 4.2.16 on 2024-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0005_alter_aparthotelservice_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="apart_services",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
