# Generated by Django 4.2.16 on 2024-12-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0005_alter_aparthotelservice_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aparthotelservice",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Действительна"), (2, "Удалена")],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
