# Generated by Django 4.2.16 on 2024-12-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0006_application_apart_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="apart_service",
            field=models.ForeignKey(
                blank=True,
                default=0,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apart_service",
                to="apartments.aparthotelservice",
                verbose_name="Услуги апарт-отеля",
            ),
        ),
    ]
