# Generated by Django 4.2.16 on 2024-12-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0007_application_apart_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aparthotelservice",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Действует"), (2, "Удалена")],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
